DELIMITER_CODE = "Code Delimiter"
DELIMITER_STR = "String Delimiter"
DELIMITER_VAR = "Declaration Delimiter"
DELIMITER_CONDT = "Conditionals Delimiter"
DELIMITER_END = "End of Expression Delimiter"

IDENTIFIER_VARS = "Variable Identifier"
IDENTIFIER_FUNC = "Function Identifier"
IDENTIFIER_LOOP = "Loop Identifier"

VAR_DECLARE = "Variable Declaration"
VAR_ASSIGN = "Variable Assignment"

KEYWORD_COMMENT = "Comment Keyword"
KEYWORD_ARITHMETIC = "Arithmetic Keyword"
KEYWORD_SEPERATOR = "Separator Keyword"
KEYWORD_COMPARE = "Comparison Keyword"
KEYWORD_BOOLEAN = "Boolean Keyword"
KEYWORD_CONCAT = "Concatenate Keyword"
KEYWORD_TYPECAST = "Typecasting Keyword"
KEYWORD_PRINT = "Output Keyword"
KEYWORD_INPUT = "Input Keyword"
KEYWROD_CONDT = "Conditional Keyword"
KEYWORD_LOOP = "Loop Keyword"
KEYWORD_FUNC = "Function Keyword"

LITERAL = "Literal"
LITERAL_NUMBAR = "NUMBAR Literal"
LITERAL_NUMBR = "NUMBR Literal"
LITERAL_TROOF = "TROOF Literal"
LITERAL_YARN = "YARN Literal"
LITERAL_NOOB = "NOOB Literal"